### ISSUE TITLE
Key?

### ISSUE THREAD

**Issue by Sheldonsuckz** [ligongcheng/qq_music_downloader#1]
Hi I don't know Chinese but i get an error when running the python script.
"获取key失败，正在退出。。。"
I understand that it failed to get the kay.
Anything I can do to fix this?
You can answer in Chinese obviously.

**Comment by ligongcheng** [comment]
Hi I checke the code and it runs well in my computer. 
but if your ip is not in china,you may  be blocked by Copyright restrictions
